name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Flet
        run: pip install flet
      - name: Build APK
        # La commande printf force la réponse "y" pour l'installation de Flutter
        run: printf 'y\n' | flet build apk
      - name: Find and Upload APK
        run: |
          find . -name "*.apk"
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-build-output
          # On change le chemin pour englober tout ce qui ressemble à un APK
          path: build/**/*.apk
