name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.14'
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install flet pandas openpyxl
      - name: Build APK
        env:
          FLET_NO_INPUT: "true"
        run: |
          yes | flet build apk --project la-vida-finance
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: build/apk/app-release.apk
